
export const PLAYER = {
  WALK_SPEED: 4,
  SPEED: 7,
  SPRINT_SPEED: 11,
  ACCELERATION: 18,
  DECELERATION: 14,
  ROTATION_SPEED: 10,
  JUMP_FORCE: 12,
  GROUND_DRAG: 0.1,
  AIR_DRAG: 0.02,
  MAX_HEALTH: 100,
  MASS: 1,
};

export const COMBAT = {
  ATTACK_RANGE: 2,
  ATTACK_COOLDOWN: 0.5,
  ATTACK_DURATION: 0.4,
  ATTACK_DAMAGE: 20,
  ATTACK_KNOCKBACK: 8,
  HITSTUN_DURATION: 0.3,
  COMBO_WINDOW: 0.8,
  MAX_COMBO: 3,
};

export const ENEMY = {
  MAX_HEALTH: 60,
  SPEED: 7.5,
  ACCELERATION: 13,
  DECELERATION: 9,
  ROTATION_SPEED: 7,
  ATTACK_WINDUP: 0.35,
  CHASE_RADIUS: 100,
  ATTACK_RANGE: 1.2,
  ATTACK_COOLDOWN: 0.8,
  ATTACK_DAMAGE: 20,
  ATTACK_KNOCKBACK: 6,
  MASS: 1,
  DETECTION_RADIUS: 100,
};

export const GAME = {
  SURVIVAL_TIME: 60,
};

export const PHYSICS = {
  GRAVITY: -9.81,
  FIXED_TIMESTEP: 1 / 60,
  MAX_VELOCITY: 50,
};

export const CAMERA = {
  DISTANCE: 5.4,
  SPRINT_DISTANCE: 6.7,
  HEIGHT: 2.4,
  LOOK_AHEAD: 1.5,
  SMOOTHING: 0.08,
  MIN_PITCH: -Math.PI / 3,
  MAX_PITCH: Math.PI / 4,
  ROTATION_SENSITIVITY: 0.005,
  SHAKE_INTENSITY: 0.15,
  SHAKE_DURATION: 0.1,
};

export const ANIMATION = {
  FADE_DURATION: 0.18,
  IDLE_SPEED: 1,
  WALK_SPEED: 1,
  RUN_SPEED: 1.5,
  SPRINT_SPEED: 2,
  JUMP_SPEED: 1,
  ATTACK_SPEED: 1.2,
  HIT_SPEED: 1,
  DEATH_SPEED: 0.8,
};

export const SCENE = {
  ARENA_SIZE: 30,
  GROUND_HEIGHT: -0.5,
  LIGHT_INTENSITY: 1.8,
  AMBIENT_INTENSITY: 0.55,
  SHADOW_MAP_SIZE: 2048,
  SHADOW_CAMERA_FAR: 50,
  BACKGROUND_COLOR: 0x1c2430,
};

export const UI = {
  HEALTH_BAR_WIDTH: 200,
  HEALTH_BAR_HEIGHT: 20,
  PADDING: 16,
  FONT_SIZE: 16,
};

export const INPUT = {
  MOVE_FORWARD: 'w',
  MOVE_BACKWARD: 's',
  MOVE_LEFT: 'a',
  MOVE_RIGHT: 'd',
  SPRINT: 'Shift',
  JUMP: ' ',
  ATTACK: 'Mouse0',
};
